# Generated by Django 4.0.3 on 2022-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='images',
            field=models.ImageField(default=0, upload_to='images'),
        ),
    ]
