# Generated by Django 4.0.3 on 2022-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_classes_description_classes_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
