# Generated by Django 4.0.3 on 2022-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_classes_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
