# Generated by Django 4.0.3 on 2022-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
