# Generated by Django 4.0.3 on 2022-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_age_order_description_order_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
