# Generated by Django 4.0.3 on 2022-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_product_order_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
