# Generated by Django 4.0.3 on 2022-06-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_order_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='age',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='images',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
