# Generated by Django 4.0.3 on 2022-06-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product',
        ),
    ]
