# Generated by Django 4.0.3 on 2022-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_order_items_remove_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
