# Generated by Django 4.0.3 on 2022-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob_no', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
