# Generated by Django 4.0.3 on 2022-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
