# Generated by Django 4.0.3 on 2022-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_checkout_fname_alter_checkout_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
