# Generated by Django 4.0.3 on 2022-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_checkout_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
        migrations.AddField(
            model_name='checkout',
            name='items',
            field=models.ManyToManyField(to='myapp.order'),
        ),
    ]
