# Generated by Django 4.0.3 on 2022-06-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='quantity',
        ),
    ]
